version: '3.5'

networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true
  internal:

volumes:
  mongodb-data:

services:

  app:
    image: $CICD_IMAGE_ID
    environment:
      - RMQ_HOST=bus
      - MONGO_HOST=mongodb
      - MONGO_USER=root
      - MONGO_PASSWORD=root
    networks:
      - bus
      - ingress
      - internal
    deploy:
      replicas: 1

  mongodb:
    image: mongo:4.2.24
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    networks:
      - internal
    volumes:
      - mongodb-data:/data/db
