name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn -B package -Ddocker.skip=true

      - name: Spotbugs
        run: mvn -B spotbugs:check

      - name: PMD
        run: mvn -B pmd:check

      - name: Checkstyle
        run: mvn -B checkstyle:check -Dcheckstyle.maxAllowedViolations=250

      - name: Integration Test
        run: mvn -B verify
